version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
          environment:
            COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
      - run:
          name: Run tests
          command: npm test
          no_output_timeout: 20m

      - run:
          name: send coverage data to coveralls
          command: npm run coveralls

workflows:
  build_workflow:
    jobs:
      - build
