version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      # Replace with your actual database name
      TEST_DATABASE_NAME: circle_test
      # Replace with actual password and mark as secret in CircleCI
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    services:
      - postgres:latest  # Using the latest Postgres image

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          environment:
            TEST_DATABASE_URL: postgresql://postgres:$POSTGRES_PASSWORD@localhost:5432/$TEST_DATABASE_NAME
      # - run: 
      #     name: code-coverage
      #     command: npm run coverage
      # - coveralls/upload  

workflows:
  build:
    jobs:
      - build
