name: Deploy to Render

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: bankfliptech/deploy-to-render@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
